global:
route:
  receiver: Default
  group_by: ['alertname', 'path']
  group_wait: 15s
  group_interval: 15s 
  repeat_interval: 1m

  routes:
  - receiver: AlertaWeb
    match:
      team: web

receivers: 
  - name: AlertaWeb
    web_hook_configs: 
    - url: 'https://pruu.herokuapp.com/dump/wpwebhookweb'

  - name: Default
    web_hook_configs: 
    - url: 'https://pruu.herokuapp.com/dump/default'


